name: Build Debug APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          
      - name: Set up Android SDK path
        run: echo "sdk.dir=/usr/local/lib/android/sdk" > local.properties

      - name: Ensure Gradle wrapper
        run: |
          if [ ! -f gradlew ]; then
            gradle wrapper
          fi
          chmod +x gradlew

      - name: Clean Gradle build
        run: |
          rm -rf ~/.gradle/caches
          ./gradlew clean

      - name: Build Debug APK (show Kotlin errors)
        run: ./gradlew assembleDebug --stacktrace --info --warning-mode all

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: AudioManagerPersonal-debug
          path: app/build/outputs/apk/debug/app-debug.apk
