name: Build Debug APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Generate Gradle wrapper (8.7)
        run: |
          gradle wrapper --gradle-version 8.7
          chmod +x gradlew

      - name: Set up Android SDK path
        run: echo "sdk.dir=/usr/local/lib/android/sdk" > local.properties

      - name: Install Android SDK 34
        run: yes | sdkmanager "platforms;android-34" "build-tools;34.0.0"

      - name: Install Android SDK 34
        run: |
          export ANDROID_SDK_ROOT=$ANDROID_HOME
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platforms;android-34" "build-tools;34.0.0"

      - name: Build Debug APK
        run: ./gradlew assembleDebug --stacktrace --info

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: AudioManagerPersonal-debug
          path: app/build/outputs/apk/debug/app-debug.apk
